### ISSUE TITLE
script injection

### ISSUE THREAD

**Issue by developit** [gauravtiwari/githubhire#1]
One of the profiles on this page exhibits a script injection vulnerability. Appears to be using `img` `onerror`.  The profile is [miketaylr](https://github.com/miketaylr).

http://hireables.co/members?q=repos:%3E=20+followers:%3E=250+language:javascript&page=21

<img width="533" alt="screen shot 2016-08-04 at 12 02 01 pm" src="https://cloud.githubusercontent.com/assets/105127/17409019/6901be90-5a3b-11e6-8cbe-d06b29db756a.png">

**Comment by gauravtiwari** [comment]
Hey Jason,  Apparently, I wasn't sanitising the bio. Anyway, it's fixed now. 

Thanks for pointing out 👍

**Comment by developit** [comment]
I might take a stab at porting this to Preact just for fun ;)
